name: Deploy to Kubernetes
on:
  push:
    branches:
      - "challenge-devops"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          #token_format: 'access_token'
          workload_identity_provider: 'projects/445787577000/locations/global/workloadIdentityPools/k8s-pool/providers/k8s-provider'
          service_account: 'github@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
      - uses: 'google-github-actions/setup-gcloud@v1'
      - name: Docker auth
        run: gcloud auth configure-docker \
             asia-docker.pkg.dev
      - name: Build and push docker image 
        run: |
          docker build -t asia-docker.pkg.dev/$GCP_PROJECT_ID/challege:$IMAGE_TAG .
          docker push asia-docker.pkg.dev/$GCP_PROJECT_ID/challege:$IMAGE_TAG
        working-directory: .
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        run: terraform init # -backend-config="bucket=$$TF_STATE_BUCKET_NAME" -backend-config="prefix=k8s"
        working-directory: .
      - name: Terraform Plan
        run: |
          terraform plan -destroy \
          -var="region=asia-southeast2" \
          -var="project_id=$GCP_PROJECT_ID" \
          -var="container_image=asia-docker.pkg.dev/$TF_STATE_BUCKET_NAME/challege:$IMAGE_TAG" \
          -out=PLAN
        working-directory: .
      - name: Terraform apply
        run: terraform apply PLAN
        working-directory: .
